### ISSUE TITLE
Default knot_locs for staggregate_spline

### ISSUE THREAD

**Issue by gmcdonald-sfg** [tcarleton/stagg#10]
Should `staggregate_spline` provide defaults for `knot_locs` if the user doesn't specify them? You mention in the read me "Most likely, you'd want to calculate different quantiles in your daily gridded values and choose knot_locs based on those".

Perhaps you want the package user to consciously make this calculation themselves to set the knots. If so, I think it's fine that the user must specify these manually. If this is fairly standard practice though, you could just calculate the quantiles and generate the knots automatically if the user leaves `knot_locs` blank. In this case, maybe you'd just need to add another argument for the number of knots or bins, e.g., `knot_number`, which would only be used when `knot_locs` is `NULL`.

Anyway, just a thought!

**Comment by traceybit** [comment]
thanks for the suggestion! people on our team have thought about this a lot and we've decided to not include defaults because doing so would require loading the full distribution of data and we recommend the user determine these values. however, we've made a note to add suggestions in documentation.
