### ISSUE TITLE
Readme documentation: Step 1: Defining extent

### ISSUE THREAD

**Issue by gmcdonald-sfg** [tcarleton/stagg#12]
Rather than manually defining the extent like you currently do:
```
kansas_extent <- c(-95.75, -95.25, 37.25, 37.75)
```

You could just take the bounding box of `kansans_counties` (which you create later on, but could be created here if you want). Note that `sf:st_bbox` provides the extent in a different order than how you specify it in `secondary_weights`. So you'd need to modify `secondary_weights` to use this different order for this code to work.
```
kansas_extent <- as.vector(sf::st_bbox(kansas_counties))
```

**Comment by saraorofino** [comment]
Hi @gmcdonald-sfg - this response is related to Issue #14. Thank you for pointing this out, it turns out that `raster::crop()` which is the function the `extent` argument is passed to can handle a variety of inputs for the extent. The output of `st_bbox(kansas_counties)` can be passed directly through `secondary_weights()` to `raster::crop()` without having to be converted to a vector. We have added some documentation about ways to generate an extent to the README and updated the documentation for the function to clarify that any object compatible with `raster::crop()` is an acceptable input. We really appreciate your thoughtful suggestions to improving the documentation!
