### ISSUE TITLE
Output of staggregate_* month/year/day columns

### ISSUE THREAD

**Issue by anna-boser** [tcarleton/stagg#6]
Why are the month, year, day variables output by staggregate_* strings with year_ or month_ at the beginning? Isn't this a bit redundant, and could we simply make these numbers?

**Comment by tliddell4** [comment]
My understanding of the problem (I haven't looked super deep into the issue but Sara and I have discussed it) is that at some point these months are column names, which can't begin with integers. I added the years_  just for consistency. I suppose we could trim them afterwards and coerce them to integers. This would allow for things like sorting if that's important to the user.

**Comment by saraorofino** [comment]
@anna-boser @tliddell4 we did talk about using `lubridate` to extract the dates from the layer names and try and have the output in date form, but as Tyler mentioned the issue is that these layer names become column names before the data are collapsed into long format. When the climate raster is first converted to a data.table each raster layer becomes a column (so the data have 365 columns for a year) and the raster layer name becomes the column name, then the data are pivoted into a long format. Initially we wanted to try and extract dates so that we could aggregate to daily values based on date instead of assuming each set of 24 layers is one day. We also wanted to avoid the hard coding of the layer names in case all era5 data don't share this structure (although so far they have). I don't think there's a way around hardcoding at least something because the layers names have a format of `X.year.month.day.hour.min.sec` and `lubridate` can't extract the date if the layer name begins with a character. I have two possibilities neither of which generalize so both are making assumptions about the layer names and/or the structure of the era5 data. 

Two things we could try: 

1. Retain original era5 layer names `X.year.month.day.hour.min.sec`. Keep the daily aggregation the same averaging or summing over each set of 24 layers (not based on name) and the `layer_names` object would keep one of every 24 layers (e.g. one layer per day but hour.min.sec would be arbitrary). In the transformations these layer names are columns and then once the data are pivoted to long form we use the following transformation on the `date` column of `clim_dt`: 
```
clim_dt[, date := str_remove(date, 'X')]
clim_dt[, date := lubridate::as_date(date)]
```
The pro of this approach is that we do minimal hard coding on the layer names and the only assumption we make about the names is that they all begin with an X (alternatively we could remove the first character so it would work for any letter - still assuming that there is a letter prefacing the dates). However, we are still making the assumption about the layer positions, e.g. that there are 24 layers per day and they are all in a row (layers 1-24 = first day, layers 25-48 = second day). 

2. Substring the original era5 layer names to remove the `hour.min.sec`, so for a given day all 24 layers should have the same name `X.year.month.day`. We can then try to index the daily aggregation using these layer names. The names become the column headings then are collapsed to the date column and we do the same set of transformations to output a date: 
```
clim_dt[, date := str_remove(date, 'X')]
clim_dt[, date := lubridate::as_date(date)]
```
The pro of this is that we can try and do the daily transformations based on the layer names to ensure that all layers for a given day are correctly grouped regardless of what order the layers are in. However, we are still hard coding two parts related to the layer names, we are assuming they all have the same structure when we substring to remove the hours.min.sec and we are assuming they all begin with X (or another character).
